name: Test libgp_parser

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configuring CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Building Project
        run: cmake --build build --config Release

      - name: Running Tests
        run: ctest --test-dir build --output-on-failure
